<<<<<<< HEAD
# Generated by Django 4.0.1 on 2022-03-07 06:58
=======
# Generated by Django 4.0.1 on 2022-03-02 05:36
>>>>>>> cc211a397fdeca62c41250165c08d2b64aa99404

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloodbank', '0001_initial'),
<<<<<<< HEAD
        ('vaccine', '0001_initial'),
=======
>>>>>>> cc211a397fdeca62c41250165c08d2b64aa99404
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='VaccineStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('vaccine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccines')),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> cc211a397fdeca62c41250165c08d2b64aa99404
            name='BloodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
<<<<<<< HEAD
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbank.bloodgroup')),
=======
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbank.bloodgroups')),
>>>>>>> cc211a397fdeca62c41250165c08d2b64aa99404
            ],
        ),
    ]
